- targets: ['10.0.90.1']
  labels:
    device_type: network
    name: fortigate-40f
- targets: ['10.0.90.11']
  labels:
    device_type: switch
    name: hpe-5130
- targets: ['10.0.90.100']
  labels:
    device_type: vmware
    name: vcenter
